# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'logistEx-ios-1394' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for logistEx-ios-1394
  pod 'NVActivityIndicatorView'
  pod 'SDWebImage'
  pod 'IQKeyboardManagerSwift'
  pod "PKCCrop"
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'SkyFloatingLabelTextField'
  pod 'Alamofire', '~> 4.6'
  pod 'FSCalendar'
  pod 'EmptyStateKit'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'Lightbox'
  pod 'SwiftSignatureView'
  pod 'GoogleSignIn'
  
  target 'logistEx-ios-1394Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'logistEx-ios-1394UITests' do
    # Pods for testing
  end

end
